name = "mongoid"
title = "Mongoid"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv"
              ]

toc_landing_pages = [
    "/quick-start"
    ]

[constants]
rails-6-version = 6.0
rails-7-version = 7.1
odm = "Mongoid"
version = "9.0"
full-version = "{+version+}.2"
ruby-driver = "Ruby driver"
language = "Ruby"
quickstart-app-name = "my-app"
feedback-widget-title = "Feedback"
