git:
  repo: 'mongodb/docs-mongoid'
  remote:
    upstream: 'mongodb/docs-mongoid'
    tools: 'mongodb/docs-tools'
project:
  name: 'mongoid'
  tag: 'mongoid'
  url: 'https://docs.mongodb.com/mongoid'
  title: 'Mongoid Manual'
  branched: true
version:
  release: '7.5'
  branch: '7.5'
system:
  runstate:
    serial_sphinx: publish
  files:
    - 'intersphinx.yaml'
    - 'integration.yaml'
    - 'sphinx_local.yaml'
    - 'push.yaml'
    - htaccess: ['htaccess.yaml']
assets:
  - branch: master
    path: build/docs-tools
    repository: https://github.com/mongodb/docs-tools.git
  - branch: 7.5-stable
    path: build/mongoid-7.5
    repository: https://github.com/mongodb/mongoid.git
paths:
  output: 'build'
  source: 'source-7.5'
  includes: 'source-7.5/includes'
  images: 'source-7.5/images'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
  locale: 'locale'

...
